[package]
name = "voratu"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.8"
tokio = { version = "1.0.0", features = ["full"] }
serde_yaml = "0.9.33"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
rust-crypto = "0.2.36"